<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Models\Libro.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>App.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
